//
//  UIColor+ACAdditions.swift
//
//  Generated by Zeplin on 10/17/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	@nonobjc class var acStrawberry: UIColor { 
		return UIColor(red: 243.0 / 255.0, green: 61.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acWhite: UIColor { 
		return UIColor(white: 240.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acWhiteTwo: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acWhiteTwo50: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.5)
	}

	@nonobjc class var acWhiteTwo30: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.3)
	}

	@nonobjc class var acWhiteTwo0: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.0)
	}

	@nonobjc class var acBlack: UIColor { 
		return UIColor(white: 0.0, alpha: 1.0)
	}

	@nonobjc class var acCharcoalGrey: UIColor { 
		return UIColor(red: 56.0 / 255.0, green: 61.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acWhiteThree: UIColor { 
		return UIColor(white: 217.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acCoolGrey: UIColor { 
		return UIColor(red: 142.0 / 255.0, green: 145.0 / 255.0, blue: 147.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var acSlateGrey: UIColor { 
		return UIColor(red: 100.0 / 255.0, green: 104.0 / 255.0, blue: 106.0 / 255.0, alpha: 1.0)
	}
}
